### ISSUE TITLE
Json dosyasinda birden fazla kayit setlemek

### ISSUE THREAD

**Issue by nkratastr** [Dev-team01-Techpro/springboot-mini-film-app#1]
Postmande create methoduyla bir kayit girilebiliyor ancak birden fazla kaydi ayni json dosyasinda create methoduyla girmeye calistigimizda asagidaki hatayi veriyor. 

"timestamp": "2023-11-18T17:46:11.280+00:00",
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: Cannot deserialize value of type `com.janavar.springfilmapp.domain.Film` from Array value (token `JsonToken.START_ARRAY`); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `com.janavar.springfilmapp.domain.Film` from Array value (token `JsonToken.START_ARRAY`)\n at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1]",
    "path": "/films"

**Comment by sinansarikaya** [comment]
Çünkü tek kayıt girme aktif. Uygulamada birden fazla kayıt girme iznini vermedik.

**Comment by nkratastr** [comment]
http://localhost:8080/films bu endpointte tek film ekleme
http://localhost:8080/films/films bu endpointte de film listesi ekleme calisiyor.
Ikisini ayni endpointte denedim ama tekli film eklemede JSON dosyasinda [ ] parantezlerini istiyor. Yoksa hata veriyor.

 [ ] parantezleri eklenirse hem tekli hem listeyi destekliyor.
